CREATE DATABASE sistema_notas;
use sistema_notas;

CREATE USER 'usuario_notas'@'localhost' IDENTIFIED BY 'contrasena123';
GRANT ALL PRIVILEGES ON sistema_notas.* TO 'usuario_notas'@'localhost';
FLUSH PRIVILEGES;
SELECT user FROM mysql.user;
CREATE TABLE `NOTA` (
  `ID` BIGINT auto_increment,
  `ESTUDIANTE` VARCHAR(60),
  `CURSO` VARCHAR(40),
  `ACTIVIDADES` INT,
  `PARCIAL1` INT,
  `PARCIAL2` INT,
  `EXAMEN_FINAL` INT,
  `TOTAL` INT,
  PRIMARY KEY (`ID`)
);
SELECT * FROM NOTA;
delete from nota where id = 13;
SELECT * FROM NOTA WHERE ID = 11;
insert into NOTA (ESTUDIANTE,ACTIVIDADES,PARCIAL1,PARCIAL2,EXAMEN_FINAL,TOTAL) VALUES ('JOSE GABRIEL',30,10,10,25,75);
ALTER TABLE NOTA RENAME COLUMN PUNTAJE_TOTAL TO TOTAL;
ALTER TABLE NOTA drop COLUMN PARCIAL2;
ALTER TABLE NOTA DROP COLUMN CURSO;
ALTER TABLE NOTA DROP COLUMN TOTAL;
ALTER TABLE NOTA DROP COLUMN parcial1;
ALTER TABLE NOTA DROP COLUMN parcial2;